import { Poppins } from "next/font/google";
import "./globals.css";

const poppa = Poppins({
  weight: ["100","200","400","600", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "BLOG POST",
  description: "Generated by Kavija & Thilina",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppa.className}
      >
        {children}
      </body>
    </html>
  );
}
