import { Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar";

const poppa = Poppins({
  weight: ["100","200","400","600", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "BLOG POST",
  description: "Generated by Kavija & Thilina",
};

export default function RootLayout({ children }) {
  return (

    <div
    className={poppa.className}
    >
    <Navbar/>
    {children}
    </div>

  );
}
